export const GRAMMAR_VERSION='0.14-exp-P';
export const EXPERIMENT_ID='P1-P_COMPONENT_COMPATIBLE_OPENING_PLACEMENT';
export const DOMAIN_SEED='inthebox.es';
export const CONTAINMENT_MARGIN=4;
export const MIN_CHILD_WIDTH=12;
export const MIN_CHILD_HEIGHT=12;
export const DORMANT_THRESHOLD=12;
export const RETIREMENT_THRESHOLD=28;
export const TRACE_LIFETIME=40;
export const PRESSURE_INCREMENT=.15;
export const PRESSURE_RELAXATION=.05;
export const OPENING_THRESHOLD=.9;
export const CLOSURE_THRESHOLD=24;
export const PRESSURE_DISCHARGE=0;
export const REOPEN_COOLDOWN=12;
export const ADMISSION_WIDTH=1;
export const TOPOLOGICAL_COST=0.5;
export const TERRITORY_OVERLAP_TOLERANCE=0;
export const TERRITORY_SEARCH_LIMIT=64;
export const GEOMETRY_EPSILON=1e-9;
export const OBJECT_POINT_EPSILON=.25;
export const RULES=[
 ['CONTAINMENT','Each child belongs to exactly one parent box and remains geometrically inside it.'],
 ['CAPACITY','Finite capacity turns occupancy into pressure.'],
 ['DIVISION','Sustained pressure can create a nested box only when a valid region remains.'],
 ['AFFINITY','Objects evaluate potential connections according to deterministic state.'],
 ['TOPOLOGY','A connection spanning more containment boundaries carries greater local friction.'],
 ['SIGNIFICANCE','Candidate strength combines raw affinity with topological cost.'],
 ['ATTENTION','Each current object has finite local attention and selects its strongest effective demand for this generation.'],
 ['MUTUALITY','A demand is admitted only when the selected pair is reciprocally significant in the current candidate field.'],
 ['RELATION','Admitted demand attempts a connection across containment ancestry; all separating boundaries must be passable.'],
 ['PRESSURE','Blocked connectivity adds deterministic pressure to closed boundaries; absent demand relaxes it.'],
 ['OPENING','Sufficient pressure creates a causally recorded opening and discharges its accumulated pressure.'],
 ['RELAXATION','An unused opening closes after 24 generations when no established relation depends on it.'],
 ['LIFECYCLE','Inactive objects become dormant, may reactivate, then retire into temporary traces before erasure.'],
 ['PERSISTENCE','Retired structures remain as historical traces until deterministic erasure.'],
 ['TRACEABILITY','Admitted demand and established relations retain deterministic causal provenance.'],
 ['TERRITORY','Siblings claim distinct finite regions inside their parent; shared boundary contact is permitted.'],
 ['RESIDUAL','A division consumes one axis of a viable free rectangle while preserving a contiguous residual when another minimum child can fit.'],
 ['SATURATION','When no legal territory remains for another child, a box remembers that its territorial capacity is exhausted.'],
 ['HABITAT','A box may directly contain an object only where it retains exclusive point territory.'],
 ['HABITAT BLOCK','A box-specific creation desire is recorded and blocked when its direct habitat is exhausted.'],
 ['OCCUPANCY','A new child may not positively contain an ACTIVE or DORMANT object directly owned by its dividing parent.'],
 ['OCCUPANCY BLOCK','Current occupancy can block a geometrically available child claim without making the parent permanently saturated.']
];
export function hashString(input){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;}
export function rng(seed){let s=hashString(String(seed))||1;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function fingerprint(value){return hashString(JSON.stringify(value)).toString(16).padStart(8,'0');}
function totals(){return{objectsCreated:1,objectsReactivated:0,objectsRetired:0,tracesCreated:0,tracesErased:0,objectCreationDesires:0,objectCreationHabitatBlocked:0,habitatExhaustionTransitions:0,habitatSearchesAvoided:0,relationsRemovedByRetirement:0,relationAttempts:0,sameContainerAttempts:0,crossBoundaryAttempts:0,blockedRelationAttempts:0,successfulRelationAttempts:0,relationsEnabledByNewOpenings:0,openingsCreated:0,openingsClosed:0,openingsReopened:0,potentialPairs:0,eligibleCandidates:0,localSelections:0,mutualMatches:0,admittedDemands:0,nonAdmittedCandidates:0,topologyCostRejected:0,admittedDistance0:0,admittedDistance1:0,admittedDistance2:0,admittedDistance3:0,admittedDistance4Plus:0,divisionRequests:0,divisionsSucceeded:0,divisionsBlocked:0,geometricScarcityBlocks:0,divisionBlockedInsufficientWidth:0,divisionBlockedInsufficientHeight:0,divisionBlockedNoFreeTerritory:0,trueSaturationBlocks:0,falseScarcityBlocks:0,residualPreservationRejections:0,terminalTerritoriesCreated:0,saturationTransitions:0,saturationSuppressedDesires:0,allocatorInvocations:0,failedAllocationSearches:0,allocatorSearchesAvoided:0,allocatorSearchesAfterSaturation:0,falseSaturations:0,saturationReversals:0,successfulDivisionsBySaturated:0,candidateChildClaimsExamined:0,candidateClaimsRejectedOccupancy:0,occupancyBlockedDivisions:0,trueOccupancyBlocks:0,falseOccupancyBlocks:0,occupancyBlockActiveObjects:0,occupancyBlockDormantObjects:0};}
export function genesis(){return{generation:0,boxes:[{id:'root',parent:null,depth:0,x:7,y:7,w:86,h:86,capacity:8,occupancy:2,pressure:.25,birth:0,state:'active',territoriallySaturated:false,objectHabitatExhausted:false}],objects:[{id:'object-0',parent:'root',depth:1,x:38,y:44,mass:1,affinity:2,birth:0,lastActivity:0,lifecycle:'ACTIVE',lifecycleEvents:[{state:'ACTIVE',generation:0,cause:'GENESIS'}]}],openings:[],relations:[],traces:[],boundaryPressure:{},events:['GENESIS'],diagnostics:totals()};}
function boxesById(s){return new Map(s.boxes.map(b=>[b.id,b]));}
function relationKey(a,b){return[a,b].sort().join('|');}
function ancestry(s,id){const boxes=boxesById(s),path=[];let c=id,guard=0;while(c!==null){path.unshift(c);const b=boxes.get(c);if(!b)break;c=b.parent;if(++guard>s.boxes.length)break;}return path;}
export function separatingBoundaries(s,a,b){if(a===b)return[];const x=ancestry(s,a),y=ancestry(s,b);let i=0;while(i<Math.min(x.length,y.length)&&x[i]===y[i])i++;return[...x.slice(i),...y.slice(i)];}
export function containmentViolations(s){const boxes=boxesById(s);return s.boxes.filter(c=>c.parent!==null).filter(c=>{const p=boxes.get(c.parent);return!p||c.x<p.x+CONTAINMENT_MARGIN||c.y<p.y+CONTAINMENT_MARGIN||c.x+c.w>p.x+p.w-CONTAINMENT_MARGIN||c.y+c.h>p.y+p.h-CONTAINMENT_MARGIN;});}
function eligible(s){return s.objects.filter(o=>o.lifecycle==='ACTIVE'||o.lifecycle==='DORMANT');}
function openFor(s,id){return s.openings.find(o=>o.box===id&&o.open);}
function validChild(p,ix,iy,w,h){const x=p.x+ix,y=p.y+iy;return w>=MIN_CHILD_WIDTH&&h>=MIN_CHILD_HEIGHT&&x>=p.x+CONTAINMENT_MARGIN&&y>=p.y+CONTAINMENT_MARGIN&&x+w<=p.x+p.w-CONTAINMENT_MARGIN&&y+h<=p.y+p.h-CONTAINMENT_MARGIN;}
function area(r){return Math.max(0,r.w)*Math.max(0,r.h);}
function overlap(a,b){const x=Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)),y=Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));return x*y;}
function subtract(base,obstacle){const ix=Math.max(base.x,obstacle.x),iy=Math.max(base.y,obstacle.y),ax=Math.min(base.x+base.w,obstacle.x+obstacle.w),ay=Math.min(base.y+base.h,obstacle.y+obstacle.h);if(ax-ix<=GEOMETRY_EPSILON||ay-iy<=GEOMETRY_EPSILON)return[base];const out=[];if(iy>base.y+GEOMETRY_EPSILON)out.push({x:base.x,y:base.y,w:base.w,h:iy-base.y});if(ay<base.y+base.h-GEOMETRY_EPSILON)out.push({x:base.x,y:ay,w:base.w,h:base.y+base.h-ay});if(ix>base.x+GEOMETRY_EPSILON)out.push({x:base.x,y:iy,w:ix-base.x,h:ay-iy});if(ax<base.x+base.w-GEOMETRY_EPSILON)out.push({x:ax,y:iy,w:base.x+base.w-ax,h:ay-iy});return out.filter(r=>r.w>GEOMETRY_EPSILON&&r.h>GEOMETRY_EPSILON);}
function freeTerritories(s,p){let free=[{x:p.x+CONTAINMENT_MARGIN,y:p.y+CONTAINMENT_MARGIN,w:p.w-CONTAINMENT_MARGIN*2,h:p.h-CONTAINMENT_MARGIN*2}];for(const child of s.boxes.filter(b=>b.parent===p.id))free=free.flatMap(r=>subtract(r,child));return free;}
export function freeRegionAudit(s,p){const free=freeTerritories(s,p),viable=free.filter(r=>r.w>=MIN_CHILD_WIDTH&&r.h>=MIN_CHILD_HEIGHT);return{free,viable,unusedArea:free.reduce((n,r)=>n+area(r),0),viableArea:viable.reduce((n,r)=>n+area(r),0),unusableArea:free.filter(r=>r.w<MIN_CHILD_WIDTH||r.h<MIN_CHILD_HEIGHT).reduce((n,r)=>n+area(r),0)};}
function pointInPositiveInterior(r,x,y){return x>r.x+GEOMETRY_EPSILON&&y>r.y+GEOMETRY_EPSILON&&x<r.x+r.w-GEOMETRY_EPSILON&&y<r.y+r.h-GEOMETRY_EPSILON;}
function currentDirectOccupants(s,p){return s.objects.filter(o=>o.parent===p.id&&(o.lifecycle==='ACTIVE'||o.lifecycle==='DORMANT'));}
const SATURATION_DIAGNOSTICS=['saturationTransitions','saturationSuppressedDesires','allocatorInvocations','failedAllocationSearches','allocatorSearchesAvoided','allocatorSearchesAfterSaturation','falseSaturations','saturationReversals','successfulDivisionsBySaturated','objectCreationDesires','objectCreationHabitatBlocked','habitatExhaustionTransitions','habitatSearchesAvoided'];
export function structuralProjection(s){const out=structuredClone(s);out.boxes=out.boxes.map(({territoriallySaturated,saturatedAtGeneration,saturationReason,viableRegionCountAtSaturation,freeAreaAtSaturation,viableFreeAreaAtSaturation,objectHabitatExhausted,habitatExhaustedAtGeneration,habitatExhaustionReason,...b})=>b);for(const k of SATURATION_DIAGNOSTICS)delete out.diagnostics[k];out.events=out.events.filter(e=>!e.startsWith('SATURATION ')&&!e.startsWith('DIVISION DESIRE SUPPRESSED')&&!e.startsWith('HABITAT EXHAUSTED')&&!e.startsWith('OBJECT CREATION HABITAT BLOCKED'));return out;}
export function inheritedFingerprint(s){const p=structuralProjection(s);p.objects=p.objects.map(o=>Object.fromEntries(Object.entries(o).filter(([key])=>key!=='legacyX'&&key!=='legacyY').map(([key,value])=>[key,key==='x'?(o.legacyX??value):key==='y'?(o.legacyY??value):value])));p.traces=p.traces.map(t=>{if(t.kind!=='OBJECT')return t;const source=s.objects.find(o=>o.id===t.sourceObject);return source?Object.fromEntries(Object.entries(t).map(([key,value])=>[key,key==='x'?(source.legacyX??source.x):key==='y'?(source.legacyY??source.y):value])):t;});const hadState=p.events.some(e=>e.startsWith('STATE '));if(hadState){const inheritedState='STATE '+fingerprint({...p,events:[],diagnostics:undefined});p.events=p.events.filter(e=>!e.startsWith('STATE '));p.events.push(inheritedState);}return fingerprint(p);}
function residualsAfter(r,candidate,axis){if(axis==='x'){return[{x:candidate.x+candidate.w,y:r.y,w:r.x+r.w-(candidate.x+candidate.w),h:r.h}].filter(x=>x.w>GEOMETRY_EPSILON);}return[{x:r.x,y:candidate.y+candidate.h,w:r.w,h:r.y+r.h-(candidate.y+candidate.h)}].filter(x=>x.h>GEOMETRY_EPSILON);}
function claimTerritory(s,p,random,overlapTolerance=TERRITORY_OVERLAP_TOLERANCE,occupants=[]){const audit=freeRegionAudit(s,p);if(overlapTolerance>0)return{reason:'RELAXATION_DISABLED',audit,candidateClaimsExamined:0,candidateClaimsRejectedOccupancy:0,occupancyBlockers:[]};if(!audit.viable.length)return{reason:audit.free.length?'NO_REGION_SUPPORTS_MINIMUM':'NO_FREE_REGION',audit,candidateClaimsExamined:0,candidateClaimsRejectedOccupancy:0,occupancyBlockers:[]};const ordered=[...audit.viable].sort((a,b)=>area(b)-area(a)||b.w-a.w||b.h-a.h||a.y-b.y||a.x-b.x);let candidateClaimsExamined=0,candidateClaimsRejectedOccupancy=0,occupancyBlockers=[];for(const r of ordered){const axis=r.w>r.h?'x':r.h>r.w?'y':random()>.5?'x':'y';const dimension=axis==='x'?r.w:r.h;const reserve=dimension>=MIN_CHILD_WIDTH*2;const ratio=.34+random()*.2;const claim=reserve?Math.max(MIN_CHILD_WIDTH,Math.min(dimension-MIN_CHILD_WIDTH,dimension*ratio)):dimension;const candidate=axis==='x'?{x:r.x,y:r.y,w:claim,h:r.h}:{x:r.x,y:r.y,w:r.w,h:claim};if(!validChild(p,candidate.x-p.x,candidate.y-p.y,candidate.w,candidate.h))continue;candidateClaimsExamined++;const blockers=occupants.filter(o=>pointInPositiveInterior(candidate,o.x,o.y));if(blockers.length){candidateClaimsRejectedOccupancy+=1;occupancyBlockers.push(...blockers.map(o=>({id:o.id,lifecycle:o.lifecycle,x:o.x,y:o.y})));s.events.push('DIVISION CANDIDATE REJECTED OCCUPANCY '+p.id+' '+blockers.map(o=>o.id).join(','));continue;}const residuals=residualsAfter(r,candidate,axis);const residualViable=residuals.filter(x=>x.w>=MIN_CHILD_WIDTH&&x.h>=MIN_CHILD_HEIGHT);return{...candidate,axis,ratio:claim/dimension,source:r,residuals,residualViable,terminal:residualViable.length===0,reason:'OK',audit,candidateClaimsExamined,candidateClaimsRejectedOccupancy,occupancyBlockers};}return{reason:candidateClaimsRejectedOccupancy?'OCCUPANCY_BLOCK':'NO_REGION_SUPPORTS_MINIMUM',audit,candidateClaimsExamined,candidateClaimsRejectedOccupancy,occupancyBlockers};}
function retire(s,o,g){o.lifecycle='RETIRED';o.retiredAt=g;o.traceExpiry=g+TRACE_LIFETIME;o.lifecycleEvents.push({state:'RETIRED',generation:g,cause:'INACTIVITY'});s.traces.push({id:'trace-'+o.id,kind:'OBJECT',sourceObject:o.id,parent:o.parent,x:o.x,y:o.y,created:o.birth,lastActive:o.lastActivity,retiredAt:g,expiry:o.traceExpiry});s.diagnostics.objectsRetired++;s.diagnostics.tracesCreated++;s.events.push('RETIRE '+o.id);}
export function exclusivePointRegions(s,parent){return freeTerritories(s,parent).map(r=>({x:r.x+OBJECT_POINT_EPSILON,y:r.y+OBJECT_POINT_EPSILON,w:r.w-OBJECT_POINT_EPSILON*2,h:r.h-OBJECT_POINT_EPSILON*2})).filter(r=>r.w>GEOMETRY_EPSILON&&r.h>GEOMETRY_EPSILON);}
export function directHabitatAudit(s,parent){const regions=exclusivePointRegions(s,parent),area=regions.reduce((n,r)=>n+r.w*r.h,0);return{available:regions.length>0,regions:regions.length,area,minimum:regions.length?Math.min(...regions.map(r=>r.w*r.h)):0,maximum:regions.length?Math.max(...regions.map(r=>r.w*r.h)):0};}
function chooseExclusivePoint(s,parent,regionRandom,xRandom,yRandom){const regions=exclusivePointRegions(s,parent);if(!regions.length)return null;const total=regions.reduce((n,r)=>n+r.w*r.h,0);let target=regionRandom*total,region=regions[regions.length-1];for(const candidate of regions){const weight=candidate.w*candidate.h;if(target<=weight){region=candidate;break;}target-=weight;}return{x:region.x+region.w*xRandom,y:region.y+region.h*yRandom,regions};}
function portalPoint(b,side,at){return side%2===0?{x:b.x+b.w*at,y:side===0?b.y:b.y+b.h}:{x:side===1?b.x+b.w:b.x,y:b.y+b.h*at};}
function portalUsable(s,boundary,side,at){const p=portalPoint(boundary,side,at),delta=1e-7,parentProbe={x:p.x+(side===1?delta:side===3?-delta:0),y:p.y+(side===0?-delta:side===2?delta:0)},parent=s.boxes.find(x=>x.id===boundary.parent);if(!parent||!pointInPositiveInterior(parent,parentProbe.x,parentProbe.y))return false;const siblings=s.boxes.filter(x=>x.parent===parent.id&&x.id!==boundary.id);if(siblings.some(x=>pointInPositiveInterior(x,parentProbe.x,parentProbe.y)))return false;const own={x:p.x+(side===3?delta:side===1?-delta:0),y:p.y+(side===0?delta:side===2?-delta:0)};return pointInPositiveInterior(boundary,own.x,own.y)&&!s.boxes.filter(x=>x.parent===boundary.id).some(x=>pointInPositiveInterior(x,own.x,own.y));}
function relationOpeningCompatible(s,attempt,boundaryOverride=null){const a=s.objects.find(o=>o.id===attempt.from),b=s.objects.find(o=>o.id===attempt.to);if(!a||!b)return false;const boundaries=separatingBoundaries(s,a.parent,b.parent);for(const id of boundaries){const box=s.boxes.find(x=>x.id===id),op=boundaryOverride&&boundaryOverride.box===id?boundaryOverride:s.openings.find(x=>x.box===id&&x.open);if(!op||!portalUsable(s,box,op.side,op.at))return false;}return true;}
function compatibleOpening(s,boundaryId,attempt,sideDraw,atDraw){const boundary=s.boxes.find(x=>x.id===boundaryId);if(!boundary)return null;const candidates=[];for(let side=0;side<4;side++)for(const at of [.2,.3,.4,.5,.6,.7,.8])if(portalUsable(s,boundary,side,at))candidates.push({side,at});if(!candidates.length)return null;const index=Math.min(candidates.length-1,Math.floor(atDraw*candidates.length));return candidates[(index+Math.floor(sideDraw*4))%candidates.length];}
function makeOpening(s,b,g,attempt,random){let existing=s.openings.find(o=>o.box===b);if(existing&&existing.open)return;if(existing&&existing.closedAt!==null&&g-existing.closedAt<REOPEN_COOLDOWN)return;const pressure=s.boundaryPressure[b]||0;if(existing){existing.open=true;existing.openedAt=g;existing.lastUse=g;existing.closedAt=null;existing.reopens++;existing.pressureAtOpen=pressure;existing.pressureAfterOpen=PRESSURE_DISCHARGE;s.diagnostics.openingsReopened++;s.events.push('REOPEN '+b);}else{const boundary=s.boxes.find(x=>x.id===b),position=compatibleOpening(s,b,attempt,random(),random());if(!position){s.events.push('OPENING DEFERRED '+b+' COMPONENT INCOMPATIBLE');return;}s.openings.push({id:'opening-'+b,box:b,open:true,openedAt:g,lastUse:g,closedAt:null,reopens:0,pressureAtOpen:pressure,pressureAfterOpen:PRESSURE_DISCHARGE,cause:'BLOCKED_RELATION_PRESSURE',triggeringAttempt:attempt.id,triggeringObjects:[attempt.from,attempt.to],side:position.side,at:position.at});s.diagnostics.openingsCreated++;s.events.push('OPENING '+b+' COMPONENT COMPATIBLE');}s.boundaryPressure[b]=PRESSURE_DISCHARGE;}
function recordActivity(s,objects,g){const seen=new Set();for(const o of objects){if(seen.has(o.id))continue;seen.add(o.id);o.lastActivity=g;if(o.lifecycle==='DORMANT'){o.lifecycle='ACTIVE';o.lifecycleEvents.push({state:'ACTIVE',generation:g,cause:'NEW_RELATION_ACTIVITY'});s.diagnostics.objectsReactivated++;s.events.push('REACTIVATE '+o.id);}}}
function admissionScore(g,a,b){return hashString('admission:'+g+':'+relationKey(a,b));}
function topologicalDistance(s,a,b){return separatingBoundaries(s,a.parent,b.parent).length;}
function effectiveSignificance(raw,distance,cost=TOPOLOGICAL_COST){return raw-distance*cost;}
export function diagnostics(s){const active=s.objects.filter(o=>o.lifecycle==='ACTIVE').length,dormant=s.objects.filter(o=>o.lifecycle==='DORMANT').length,retired=s.objects.filter(o=>o.lifecycle==='RETIRED').length,open=s.openings.filter(o=>o.open).length,pressures=Object.values(s.boundaryPressure).filter(p=>p>0),currentRelations=s.relations.length,objectTraces=s.traces.filter(t=>t.kind==='OBJECT').length,components=[];const graph=new Map(s.objects.filter(o=>o.lifecycle!=='RETIRED').map(o=>[o.id,new Set([o.id])])) ;for(const r of s.relations){if(!graph.has(r.from)||!graph.has(r.to))continue;graph.get(r.from).add(r.to);graph.get(r.to).add(r.from);}const visited=new Set();for(const id of graph.keys())if(!visited.has(id)){const stack=[id],set=new Set();while(stack.length){const x=stack.pop();if(visited.has(x))continue;visited.add(x);set.add(x);for(const y of graph.get(x)||[])if(!visited.has(y))stack.push(y);}components.push(set.size);}return{...s.diagnostics,activeObjects:active,dormantObjects:dormant,retiredRecords:retired,currentObjects:active+dormant,totalObjectRecords:s.objects.length,activeRelations:currentRelations,currentTraces:s.traces.length,currentObjectTraces:objectTraces,openBoundaries:open,closedBoundaries:Math.max(0,s.boxes.length-1-open),totalNestedBoundaries:Math.max(0,s.boxes.length-1),boundariesUnderPressure:pressures.length,totalBoundaryPressure:pressures.reduce((a,b)=>a+b,0),meanNonzeroPressure:pressures.length?pressures.reduce((a,b)=>a+b,0)/pressures.length:0,maxBoundaryPressure:pressures.length?Math.max(...pressures):0,containmentViolations:containmentViolations(s).length,largestComponent:components.length?Math.max(...components):0,oldestCurrentObject:s.objects.filter(o=>o.lifecycle!=='RETIRED').reduce((m,o)=>Math.max(m,s.generation-o.birth),0),maxOpenDuration:s.openings.filter(o=>o.open).reduce((m,o)=>Math.max(m,s.generation-o.openedAt),0)};}
export function nextState(previous,cost=TOPOLOGICAL_COST,overlapTolerance=TERRITORY_OVERLAP_TOLERANCE){const g=previous.generation+1,random=rng(DOMAIN_SEED+':0.9-exp-J:'+g+':'+inheritedFingerprint(previous)),s=structuredClone(previous);s.generation=g;s.events=[];s.openings=s.openings.map(o=>({...o}));s.relations=[...s.relations];s.diagnostics={...previous.diagnostics};s.boundaryPressure={...previous.boundaryPressure};s.boxes=s.boxes.map(b=>({...b,occupancy:Math.max(0,b.occupancy+(random()>.58?1:random()<.2?-1:0)),pressure:0}));
  const kept=[];for(const t of s.traces){if(t.kind==='OBJECT'&&g>=t.expiry){s.objects=s.objects.filter(o=>o.id!==t.sourceObject);s.diagnostics.tracesErased++;s.events.push('ERASE '+t.sourceObject);}else kept.push(t);}s.traces=kept;
  const activeBoxes=[...s.boxes];for(const box of activeBoxes){box.pressure=Math.min(1.4,box.occupancy/box.capacity);const wants=box.pressure>.82&&box.depth<3&&g%4===0&&s.boxes.length<24&&!s.boxes.some(c=>c.parent===box.id&&c.birth===g)&&random()>.35;if(wants){s.diagnostics.divisionRequests++;if(box.territoriallySaturated){s.diagnostics.divisionsBlocked++;s.diagnostics.geometricScarcityBlocks++;s.diagnostics.trueSaturationBlocks++;s.diagnostics.divisionBlockedNoFreeTerritory++;s.diagnostics.saturationSuppressedDesires++;s.diagnostics.allocatorSearchesAvoided++;s.events.push('DIVISION BLOCKED '+box.id+' '+box.saturationReason);s.events.push('DIVISION DESIRE SUPPRESSED '+box.id+' SATURATED');continue;}s.diagnostics.allocatorInvocations++;const occupants=currentDirectOccupants(s,box);const territory=claimTerritory(s,box,random,overlapTolerance,occupants);s.diagnostics.candidateChildClaimsExamined+=territory.candidateClaimsExamined||0;s.diagnostics.candidateClaimsRejectedOccupancy+=territory.candidateClaimsRejectedOccupancy||0;if(territory.reason==='OK'){const id='box-'+g+'-'+box.id;s.boxes.push({id,parent:box.id,depth:box.depth+1,x:territory.x,y:territory.y,w:territory.w,h:territory.h,capacity:3+Math.floor(random()*4),occupancy:1,pressure:.25,birth:g,state:'active',territoriallySaturated:false,objectHabitatExhausted:false});s.diagnostics.divisionsSucceeded++;if(territory.terminal)s.diagnostics.terminalTerritoriesCreated++;box.occupancy=Math.max(0,box.occupancy-2);s.events.push('DIVISION '+box.id+' → '+id+' TERRITORY '+territory.axis.toUpperCase()+' RESIDUAL');}else if(territory.reason==='OCCUPANCY_BLOCK'){s.diagnostics.divisionsBlocked++;s.diagnostics.occupancyBlockedDivisions++;s.diagnostics.trueOccupancyBlocks++;const activeBlockers=territory.occupancyBlockers.filter(o=>o.lifecycle==='ACTIVE').length,dormantBlockers=territory.occupancyBlockers.filter(o=>o.lifecycle==='DORMANT').length;s.diagnostics.occupancyBlockActiveObjects+=activeBlockers;s.diagnostics.occupancyBlockDormantObjects+=dormantBlockers;s.events.push('DIVISION BLOCKED '+box.id+' OCCUPANCY '+territory.occupancyBlockers.map(o=>o.id).join(','));}else{s.diagnostics.divisionsBlocked++;s.diagnostics.geometricScarcityBlocks++;s.diagnostics.trueSaturationBlocks++;s.diagnostics.failedAllocationSearches++;box.territoriallySaturated=true;box.saturatedAtGeneration=g;box.saturationReason=territory.reason;box.viableRegionCountAtSaturation=territory.audit.viable.length;box.freeAreaAtSaturation=territory.audit.unusedArea;box.viableFreeAreaAtSaturation=territory.audit.viableArea;s.diagnostics.saturationTransitions++;if(territory.reason==='NO_FREE_REGION')s.diagnostics.divisionBlockedNoFreeTerritory++;else s.diagnostics.divisionBlockedNoFreeTerritory++;s.events.push('DIVISION BLOCKED '+box.id+' '+territory.reason);s.events.push('SATURATION '+box.id+' '+territory.reason);}}}
  for(const box of s.boxes){const habitat=directHabitatAudit(s,box);if(!habitat.available&&!box.objectHabitatExhausted){box.objectHabitatExhausted=true;box.habitatExhaustedAtGeneration=g;box.habitatExhaustionReason='NO_DIRECT_HABITAT';s.diagnostics.habitatExhaustionTransitions++;s.events.push('HABITAT EXHAUSTED '+box.id);}}
  const leaves=s.boxes.filter(b=>b.occupancy>0);if(g%3===0&&leaves.length){s.diagnostics.objectCreationDesires++;const b=leaves[Math.floor(random()*leaves.length)],id='object-'+g,xRandom=random(),yRandom=random(),legacyX=b.x+b.w*(.25+xRandom*.5),legacyY=b.y+b.h*(.25+yRandom*.5),pointY=(xRandom*.6180339887498949+yRandom*.3819660112501051)%1,placement=b.objectHabitatExhausted?null:chooseExclusivePoint(s,b,xRandom,yRandom,pointY),mass=1+Math.floor(random()*2),affinity=Math.floor(random()*4);if(!placement){s.diagnostics.objectCreationHabitatBlocked++;s.diagnostics.habitatSearchesAvoided++;s.events.push('OBJECT CREATION HABITAT BLOCKED '+id+' in '+b.id);}else{s.objects.push({id,parent:b.id,depth:b.depth+1,x:placement.x,y:placement.y,legacyX,legacyY,mass,affinity,birth:g,lastActivity:g,lifecycle:'ACTIVE',lifecycleEvents:[{state:'ACTIVE',generation:g,cause:'CREATION'}]});b.occupancy++;s.diagnostics.objectsCreated++;s.events.push('ARRIVAL '+id+' in '+b.id);}}
  for(const o of s.objects)if(o.lifecycle==='ACTIVE'&&g-o.lastActivity>=DORMANT_THRESHOLD){o.lifecycle='DORMANT';o.dormantAt=g;o.lifecycleEvents.push({state:'DORMANT',generation:g,cause:'INACTIVITY'});s.events.push('DORMANT '+o.id);}
  const current=eligible(s),blocked=new Set(),newOpenings=new Set(),selection=new Map(),admitted=new Map();
  for(const object of current){const candidates=current.filter(other=>other.id!==object.id&&other.affinity===object.affinity).map(other=>({object:other,distance:topologicalDistance(s,object,other),raw:object.affinity,effective:effectiveSignificance(object.affinity,topologicalDistance(s,object,other),cost),tie:admissionScore(g,object.id,other.id)}));s.diagnostics.potentialPairs+=candidates.length;s.diagnostics.eligibleCandidates+=candidates.length;if(!candidates.length)continue;candidates.sort((a,b)=>b.effective-a.effective||b.tie-a.tie);const chosen=candidates.slice(0,ADMISSION_WIDTH);selection.set(object.id,new Set(chosen.map(x=>x.object.id)));s.diagnostics.localSelections+=chosen.length;s.diagnostics.nonAdmittedCandidates+=candidates.length-chosen.length;s.diagnostics.topologyCostRejected+=candidates.filter(x=>x.effective<chosen[0].effective).length;}
  for(const [from,targets] of selection)for(const to of targets)if(selection.get(to)?.has(from)){const key=relationKey(from,to);if(!admitted.has(key)){admitted.set(key,[s.objects.find(o=>o.id===from),s.objects.find(o=>o.id===to)]);s.diagnostics.mutualMatches++;s.diagnostics.admittedDemands++;}}
  for(const [key,pairObjects] of admitted){const [a,b]=pairObjects,attempt={id:'attempt-'+g+'-'+key,generation:g,from:a.id,to:b.id},boundaries=separatingBoundaries(s,a.parent,b.parent),distance=boundaries.length,pair=key.split('|'),existingRelation=s.relations.find(r=>relationKey(r.from,r.to)===key);if(distance===0)s.diagnostics.admittedDistance0++;else if(distance===1)s.diagnostics.admittedDistance1++;else if(distance===2)s.diagnostics.admittedDistance2++;else if(distance===3)s.diagnostics.admittedDistance3++;else s.diagnostics.admittedDistance4Plus++;s.diagnostics.relationAttempts++;if(!boundaries.length){s.diagnostics.sameContainerAttempts++;s.diagnostics.successfulRelationAttempts++;if(!existingRelation){s.relations.push({id:'relation-'+pair.join('--'),from:pair[0],to:pair[1],kind:'affinity',rawAffinity:a.affinity,topologicalDistance:0,topologicalCost:0,effectiveSignificance:a.affinity,requiredBoundaries:[],createdGeneration:g,createdViaOpening:false});recordActivity(s,[a,b],g);}continue;}s.diagnostics.crossBoundaryAttempts++;const closed=boundaries.filter(x=>!openFor(s,x));if(closed.length){s.diagnostics.blockedRelationAttempts++;for(const x of closed){blocked.add(x);const p=Math.min(1,(s.boundaryPressure[x]||0)+PRESSURE_INCREMENT);s.boundaryPressure[x]=p;s.events.push('PRESSURE '+x+' '+p.toFixed(2)+' from '+attempt.id);if(p>=OPENING_THRESHOLD){makeOpening(s,x,g,attempt,random);newOpenings.add(x);}}}else{s.diagnostics.successfulRelationAttempts++;const enabled=boundaries.some(x=>openFor(s,x));if(enabled){if(newOpenings.size)s.diagnostics.relationsEnabledByNewOpenings++;else s.diagnostics.relationsUsingExistingOpenings++;for(const x of boundaries){const op=openFor(s,x);if(op)op.lastUse=g;}}if(!existingRelation){s.relations.push({id:'relation-'+pair.join('--'),from:pair[0],to:pair[1],kind:'affinity',rawAffinity:a.affinity,topologicalDistance:distance,topologicalCost:distance*TOPOLOGICAL_COST,effectiveSignificance:effectiveSignificance(a.affinity,distance),requiredBoundaries:boundaries,createdGeneration:g,createdViaOpening:enabled});recordActivity(s,[a,b],g);}}}
  const relationEndpoint=new Set(s.objects.filter(o=>o.lifecycle!=='RETIRED').map(o=>o.id));s.relations=s.relations.filter(r=>relationEndpoint.has(r.from)&&relationEndpoint.has(r.to));
  for(const r of s.relations)for(const b of r.requiredBoundaries||r.boundaries||[]){const op=openFor(s,b);if(op)op.lastUse=g;}
  for(const o of s.objects)if((o.lifecycle==='ACTIVE'||o.lifecycle==='DORMANT')&&g-o.lastActivity>=RETIREMENT_THRESHOLD)retire(s,o,g);
  const retired=new Set(s.objects.filter(o=>o.lifecycle==='RETIRED').map(o=>o.id));s.relations=s.relations.filter(r=>{if(retired.has(r.from)||retired.has(r.to)){s.diagnostics.relationsRemovedByRetirement++;return false;}return true;});
  for(const op of s.openings){const dependent=s.relations.some(r=>(r.requiredBoundaries||r.boundaries||[]).includes(op.box));if(op.open&&dependent)op.lastUse=g;if(op.open&&!dependent&&g-op.lastUse>=CLOSURE_THRESHOLD){op.open=false;op.closedAt=g;s.diagnostics.openingsClosed++;s.events.push('CLOSE '+op.box);}}
  for(const b of Object.keys(s.boundaryPressure)){if(!blocked.has(b))s.boundaryPressure[b]=Math.max(0,s.boundaryPressure[b]-PRESSURE_RELAXATION);}
  if(g%5===0&&s.boxes.length>1){const old=s.boxes.filter(b=>b.birth<g-20);for(const b of old.slice(0,1))if(!s.traces.some(t=>t.kind==='BOX'&&t.id===b.id))s.traces.push({id:b.id,kind:'BOX',x:b.x,y:b.y,w:b.w,h:b.h,decay:Math.max(.15,1-(g-b.birth)/160)});}
  s.events.push('STATE '+fingerprint({...s,events:[],diagnostics:undefined}));return s;}
export function replay(generation,cost=TOPOLOGICAL_COST,overlapTolerance=TERRITORY_OVERLAP_TOLERANCE){let s=genesis();for(let i=0;i<generation;i++)s=nextState(s,cost,overlapTolerance);return s;}
